name: Movie Rank Backend Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  version_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # - name: Setup Node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version-file: '.nvmrc'

      - name: Check if version has been updated
        uses: kriasoft/check-version@v1
  
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install modules
        run: npm install eslint --save-dev
    
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx