name: Movie Rank Backend Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Check if version has been updated
        id: version-check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-url: https://raw.githubusercontent.com/Samueljit/movie-rank/main/package.json
          assume-same-version: old
          # static-checking: localIsNew

      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'

      - name: Fail if the version hasn't been changed
        if: steps.version-check.outputs.changed == 'false'
        run: 'throw "Please update the package.json version"'